test
Signed-off-by: Derek Smart <derek@grindaga.com>

diff --git a/.github/workflows/pull-request-labeled-closed.yml b/.github/workflows/pull-request-labeled-closed.yml
--- a/.github/workflows/pull-request-labeled-closed.yml
+++ b/.github/workflows/pull-request-labeled-closed.yml
@@ -6,71 +6,113 @@ on:
       - closed
 
 jobs:
-  printJob:
-    name: Print event
+  verify:
+    name: Verify Closed PR is Release Candidate
+    runs-on: ubuntu-latest
+    if: |
+      ${{ github.ref == 'main' }} &&
+      ${{ github.event.pull_request.merged }} &&
+      contains( github.event.pull_request.labels.*.name, 'Extension Release Candidate :rocket:' )
+    steps:
+      - run: echo "Starting Release ... "
+
+  build:
+    needs: [verify]
+    name: Build Artifact
     runs-on: ubuntu-latest
     steps:
-      - name: Dump GitHub context
-        env:
-          GITHUB_CONTEXT: ${{ toJson(github) }}
-        run: |
-          echo "$GITHUB_CONTEXT"
+      - uses: actions/checkout@v2
+      - name: Cache Local Maven Repository
+        uses: actions/cache@v2
+        with:
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-
+      - name: Set up JDK 11
+        uses: actions/setup-java@v2
+        with:
+          java-version: '11'
+          distribution: 'adopt'
+      - name: Build With Maven
+        run: mvn -B package -DskipTests --file pom.xml
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          name: liquibase-postgresql
+          path: target/*.jar
 
-#  integration-tests:
-#    name: Java ${{ matrix.java }}, Postgres ${{ matrix.postgres }}
-#    runs-on: ubuntu-latest
-#    if: contains( github.event.pull_request.labels.*.name, 'Extension Release Candidate :rocket:' )
-#    strategy:
-#      matrix:
-#        java: [8, 11, 16]
-#        postgres: [9, 10, 11, 12, 13]
-#    services:
-#      postgres:
-#        image: postgres:${{ matrix.postgres }}
-#        env:
-#          POSTGRES_USER: lbtest
-#          POSTGRES_PASSWORD: lbtest
-#        ports:
-#          - 5432:5432
-#    steps:
-#      - uses: actions/checkout@v2
-#      - name: Cache Local Maven Repository
-#        uses: actions/cache@v2
-#        with:
-#          path: ~/.m2/repository
-#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-#          restore-keys: |
-#            ${{ runner.os }}-maven-
-#      - name: Set up JDK ${{ matrix.java }}
-#        uses: actions/setup-java@v2
-#        with:
-#          java-version: ${{ matrix.java }}
-#          distribution: 'adopt'
-#      - name: Test With Maven
-#        run: mvn clean verify --file pom.xml
-#
-#  build:
-#    needs: [integration-tests]
-#    name: Build Artifacts
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v2
-#      - name: Cache Local Maven Repository
-#        uses: actions/cache@v2
-#        with:
-#          path: ~/.m2/repository
-#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-#          restore-keys: |
-#            ${{ runner.os }}-maven-
-#      - name: Set up JDK 11
-#        uses: actions/setup-java@v2
-#        with:
-#          java-version: '11'
-#          distribution: 'adopt'
-#      - name: Build With Maven
-#        run: mvn -B package -DskipTests --file pom.xml
-#      - name: Upload Artifacts
-#        uses: actions/upload-artifact@v2
-#        with:
-#          name: liquibase-postgresql
-#          path: target/*.jar
+  draft-release:
+    needs: [ build ]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Cache Local Maven Repository
+        uses: actions/cache@v2
+        with:
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-
+
+      - name: Set up JDK 11
+        uses: actions/setup-java@v2
+        with:
+          java-version: '11'
+          distribution: 'adopt'
+
+      - name: Set Version Tag ENV from POM
+        run: ./.github/set-version-from-pom.sh
+
+      - run: echo $VERSION_TAG
+
+      - name: Download Artifacts
+        uses: actions/download-artifact@v2
+        with:
+          name: liquibase-postgresql
+
+      - name: Release
+        uses: softprops/action-gh-release@v1
+        with:
+          tag_name: liquibase-postgresql-$VERSION_TAG
+          draft: true
+          body: Support for Liquibase $VERSION_TAG.
+          files: liquibase-postgresql-$VERSION_TAG.jar
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  bump-pom-to-snapshot:
+    name: Prepare POM for Development
+    runs-on: ubuntu-latest
+    needs: [ draft-release ]
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
+          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
+
+      - name: Cache Local Maven Repository
+        uses: actions/cache@v2
+        with:
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-
+
+      - name: Set up JDK 11
+        uses: actions/setup-java@v2
+        with:
+          java-version: '11'
+          distribution: 'adopt'
+
+      - name: Configure git user
+        run: |
+          git config user.name "liquibot"
+          git config user.email "liquibot@liquibase.org"
+
+      - name: Bump POM Version for Development
+        run: |
+          mvn versions:set -DnextSnapshot=true
+          git add pom.xml
+          git commit -m "Version Bumped to Snapshot for Developent"
+          git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" HEAD:${{ github.base_ref }}
